sudo: false
language: go
go:
  - 1.5.1

env:
  - GO15VENDOREXPERIMENT=1

before_install:
  - wget http://apache.claz.org/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz
  - tar -zxvf zookeeper*tar.gz
  - cd zookeeper*
  - cp conf/zoo_sample.cfg conf/zoo.cfg
  - cd bin
  - ./zkServer.sh start
  - cd ../..

script:
  - go build $(go list ./... | grep -v /vendor/)
  - go fmt $(go list ./... | grep -v /vendor/)
  - go get golang.org/x/tools/cmd/vet
  - go tool vet *.go
  - go tool vet ./httpset
  - go tool vet ./mcset
  - go tool vet ./fixedset
  - go test -i -race $(go list ./... | grep -v /vendor/)
  - go test -v -race $(go list ./... | grep -v /vendor/)

